const ADD_ENTRY_REQUEST = 'ADD_ENTRY_REQUEST';
const ADD_ENTRY_SUCCESS = 'ADD_ENTRY_SUCCESS';
const ADD_ENTRY_FAILURE ='ADD_ENTRY_FAILURE';

export {
  ADD_ENTRY_REQUEST ,
  ADD_ENTRY_SUCCESS,
  ADD_ENTRY_FAILURE,
}
