const ADD_SECTION_REQUEST = 'ADD_SECTION_REQUEST';
const ADD_SECTION_SUCCESS = 'ADD_SECTION_SUCCESS';
const ADD_SECTION_FAILURE ='ADD_SECTION_FAILURE';

export {
  ADD_SECTION_REQUEST ,
  ADD_SECTION_SUCCESS,
  ADD_SECTION_FAILURE,
}
