const ENTRY_LIST_REQUEST = 'ENTRY_LIST_REQUEST';
const ENTRY_LIST_SUCCESS = 'ENTRY_LIST_SUCCESS';
const ENTRY_LIST_FAILURE = 'ENTRY_LIST_FAILURE';
export {
  ENTRY_LIST_REQUEST,
  ENTRY_LIST_SUCCESS,
  ENTRY_LIST_FAILURE,
}
