const SECTION_LIST_REQUEST = 'SECTION_LIST_REQUEST';
const SECTION_LIST_SUCCESS = 'SECTION_LIST_SUCCESS';
const SECTION_LIST_FAILURE = 'SECTION_LIST_FAILURE';
export {
  SECTION_LIST_REQUEST,
  SECTION_LIST_SUCCESS,
  SECTION_LIST_FAILURE,
}
